from enum import Enum

class EndianState(Enum):
    Default = -1
    Big = 0
    Little = 1

def test_read_numeric(
    endian_data: EndianState, read_offset: bool, read_into: bool
) -> None: ...
def test_read_string(endian_data: EndianState, read_offset: bool) -> None: ...
def test_write_numeric(endian_data: EndianState) -> None: ...
def test_write_string(endian_data: EndianState) -> None: ...
